# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: \.svg$
      - id: check-ast
      - id: check-xml
      - id: check-yaml
      - id: check-json
        # devcontainer.json contains comments
        exclude: .devcontainer/devcontainer\.json
      - id: check-toml
      - id: check-added-large-files
      # - id: pretty-format-json
      #   # black has its own mind of formatting Jupyter notebooks
      #   exclude: \.ipynb$|^.devcontainer/devcontainer\.json$|package-lock\.json$
      #   args:
      #     - --no-sort-keys
      #     - --autofix

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: "v17.0.6"
    hooks:
      - id: clang-format
        files: \.(c|cpp|h|hpp)(\.in)?$
        args: []

  # - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
  #   rev: "2.7.3"
  #   hooks:
  #     - id: editorconfig-checker
  #       alias: ec

  # Using this mirror lets us use mypyc-compiled black, which is about 2x faster
  # - repo: https://github.com/psf/black-pre-commit-mirror
  #   rev: "23.3.0"
  #   hooks:
  #     - id: black
  #     - id: black-jupyter
