name: Publish DPsim package to Python Package Index (PyPI)

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  build-sdist:
    name: Build DPsim source distribution
    runs-on: ubuntu-24.04
    container: sogno/dpsim:dev
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Build DPsim source distribution
      shell: bash
      run: python3 -m build --sdist --outdir dist/

    - name: Archive Python source distribution
      uses: actions/upload-artifact@v4
      with:
        name: dist-source
        path: dist/

  build-wheels:
    name: Build DPsim Python wheel
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        platform: [manylinux_x86_64]
        python: [cp39, cp310, cp311, cp312, cp313]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Build wheel
      uses: pypa/cibuildwheel@v2.23.2
      env:
        CIBW_BUILD: "${{ matrix.python }}-${{ matrix.platform }}"
      with:
        output-dir: dist

    - name: Upload wheel as artifact
      uses: actions/upload-artifact@v4
      with:
        name: dist-wheels-${{ matrix.python }}-${{ matrix.platform }}
        path: dist/

  publish:
    name: Publish wheels and source distribution to PyPI
    runs-on: ubuntu-24.04
    if: github.event_name == 'push'
    permissions:
      id-token: write
    needs:
    - build-wheels
    - build-sdist

    steps:
    - name: Download wheels from build jobs
      uses: actions/download-artifact@v4
      with:
        pattern: dist-*
        merge-multiple: true
        path: dist/

    - name: Publish distribution to Test PyPI
      uses: pypa/gh-action-pypi-publish@v1.13.0
      with:
        repository-url: https://test.pypi.org/legacy/
        skip-existing: true

    - name: Publish distribution to PyPI
      if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@v1.13.0
